console.log("Hello world");
var message;
message = 'Hello typescript';
console.log(message);
//message = 30;
var bool = [true, false];
console.log(bool[1]);
var a = 'hello';
//let a = 'hello';
//const bool: Boolean[] = [true,false];
